-- Fraga Sucatas 2.0: shared data, protected by Supabase Auth and RLS.
create schema if not exists private;
revoke all on schema private from public, anon;
grant usage on schema private to authenticated, service_role;

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique check (username = lower(username)),
  email text not null unique,
  name text not null,
  role text not null default 'CLIENTE' check (role in ('ADMIN', 'CLIENTE')),
  created_at timestamptz not null default now()
);
alter table public.profiles enable row level security;

create function private.is_admin() returns boolean language sql stable security definer
set search_path = '' as $$
  select auth.uid() is not null and exists (
    select 1 from public.profiles where id = (select auth.uid()) and role = 'ADMIN'
  );
$$;
revoke all on function private.is_admin() from public;
grant execute on function private.is_admin() to authenticated, service_role;

create policy profiles_read on public.profiles for select to authenticated
using (id = (select auth.uid()) or (select private.is_admin()));
grant select on public.profiles to authenticated;
revoke insert, update, delete on public.profiles from anon, authenticated;

create table public.customers (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete set null,
  legacy_user_id bigint,
  nome text not null check (length(trim(nome)) > 0),
  cpf_cnpj text default '', telefone text default '', whatsapp text default '',
  email text default '', endereco text default '', cidade text default '',
  estado text default '', cep text default '',
  created_at timestamptz not null default now()
);
create index customers_user_idx on public.customers(user_id);
create index customers_legacy_user_idx on public.customers(legacy_user_id);
alter table public.customers enable row level security;
create policy customers_read on public.customers for select to authenticated
using (user_id = (select auth.uid()) or (select private.is_admin()));
create policy customers_admin_write on public.customers for all to authenticated
using ((select private.is_admin())) with check ((select private.is_admin()));

create sequence public.note_number_seq;
create table public.notes (
  id bigint generated by default as identity primary key,
  public_id text not null unique default gen_random_uuid()::text,
  numero_nota text not null unique default
    ('FS-' || to_char(now() at time zone 'America/Fortaleza', 'YYYY') || '-' || lpad(nextval('public.note_number_seq')::text, 6, '0')),
  customer_id bigint not null references public.customers(id) on delete restrict,
  data_compra text not null,
  descricao text default '', observacoes text default '',
  valor_total numeric(14,2) not null default 0 check (valor_total >= 0),
  status text not null default 'VALIDA' check (status in ('VALIDA','INVALIDADA','PENDENTE')),
  public_visible_value boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  validated_at timestamptz, validated_by text
);
create index notes_customer_idx on public.notes(customer_id);
alter table public.notes enable row level security;
create policy notes_read on public.notes for select to authenticated using (
  (select private.is_admin()) or exists (
    select 1 from public.customers c where c.id = customer_id and c.user_id = (select auth.uid())
  )
);
create policy notes_admin_write on public.notes for all to authenticated
using ((select private.is_admin())) with check ((select private.is_admin()));

create table public.note_items (
  id bigint generated by default as identity primary key,
  note_id bigint not null references public.notes(id) on delete cascade,
  descricao text not null check (length(trim(descricao)) > 0),
  quantidade numeric(12,3) not null check (quantidade > 0),
  valor_unitario numeric(14,2) not null check (valor_unitario >= 0),
  valor_total numeric(14,2) generated always as (round(quantidade * valor_unitario, 2)) stored
);
create index note_items_note_idx on public.note_items(note_id);
alter table public.note_items enable row level security;
create policy items_read on public.note_items for select to authenticated using (
  (select private.is_admin()) or exists (
    select 1 from public.notes n join public.customers c on c.id = n.customer_id
    where n.id = note_id and c.user_id = (select auth.uid())
  )
);
create policy items_admin_write on public.note_items for all to authenticated
using ((select private.is_admin())) with check ((select private.is_admin()));

create table public.note_files (
  id bigint generated by default as identity primary key,
  note_id bigint not null references public.notes(id) on delete cascade,
  filename text not null, filetype text not null, filepath text not null,
  uploaded_at timestamptz not null default now()
);
create index note_files_note_idx on public.note_files(note_id);
alter table public.note_files enable row level security;
create policy files_read on public.note_files for select to authenticated using (
  (select private.is_admin()) or exists (
    select 1 from public.notes n join public.customers c on c.id = n.customer_id
    where n.id = note_id and c.user_id = (select auth.uid())
  )
);
create policy files_admin_write on public.note_files for all to authenticated
using ((select private.is_admin())) with check ((select private.is_admin()));

create table public.company_settings (
  id integer primary key default 1 check (id = 1),
  company_name text not null, trade_name text not null, cnpj text not null,
  address text, city text, state text, cep text, phone text, whatsapp text,
  instagram text, facebook text, website text, google_maps text,
  business_hours text, description text, logo_url text,
  updated_at timestamptz not null default now()
);
alter table public.company_settings enable row level security;
create policy company_read on public.company_settings for select to anon, authenticated using (true);
create policy company_admin_write on public.company_settings for all to authenticated
using ((select private.is_admin())) with check ((select private.is_admin()));

create table public.portfolio_items (
  id bigint generated by default as identity primary key,
  title text not null, category text not null, description text,
  image_url text not null, display_order integer not null default 0,
  published boolean not null default true,
  created_at timestamptz not null default now()
);
alter table public.portfolio_items enable row level security;
create policy portfolio_public on public.portfolio_items for select to anon, authenticated using (published);
create policy portfolio_admin_write on public.portfolio_items for all to authenticated
using ((select private.is_admin())) with check ((select private.is_admin()));

create table public.audit_logs (
  id bigint generated by default as identity primary key,
  user_name text not null, user_role text not null, action text not null,
  target_type text, target_id text, details text, ip_address text,
  created_at timestamptz not null default now()
);
alter table public.audit_logs enable row level security;
create policy audit_admin_read on public.audit_logs for select to authenticated
using ((select private.is_admin()));
grant select on public.audit_logs to authenticated;
revoke insert, update, delete on public.audit_logs from anon, authenticated;

grant select, insert, update, delete on public.customers, public.notes, public.note_items,
  public.note_files, public.company_settings, public.portfolio_items to authenticated;
grant select on public.company_settings, public.portfolio_items to anon;
revoke all on public.customers, public.notes, public.note_items, public.note_files, public.profiles, public.audit_logs from anon;
grant usage, select on all sequences in schema public to authenticated;

-- The trigger records metadata only; CPF and addresses are not copied into logs.
create function private.audit_change() returns trigger language plpgsql security definer
set search_path = '' as $$
declare actor public.profiles;
begin
  if auth.uid() is null then return null; end if;
  select * into actor from public.profiles where id = auth.uid();
  insert into public.audit_logs(user_name,user_role,action,target_type,target_id,details)
  values (coalesce(actor.name,'Usuário'),coalesce(actor.role,'CLIENTE'),TG_OP,TG_TABLE_NAME,
    case when TG_OP = 'DELETE' then old.id::text else new.id::text end, 'Alteração salva no banco compartilhado');
  return null;
end;
$$;
revoke all on function private.audit_change() from public, anon, authenticated;
create trigger audit_customers after insert or update or delete on public.customers for each row execute function private.audit_change();
create trigger audit_notes after insert or update or delete on public.notes for each row execute function private.audit_change();
create trigger audit_company after insert or update or delete on public.company_settings for each row execute function private.audit_change();
create trigger audit_portfolio after insert or update or delete on public.portfolio_items for each row execute function private.audit_change();

-- One transaction creates/edits both the note and its items.
create function public.save_note(payload jsonb, note_id_input bigint default null) returns jsonb
language plpgsql security invoker set search_path = '' as $$
declare saved public.notes; item jsonb;
begin
  if auth.uid() is null or not private.is_admin() then raise exception 'Acesso negado'; end if;
  perform pg_advisory_xact_lock(7242907);
  if jsonb_typeof(payload->'itens') is distinct from 'array' or jsonb_array_length(payload->'itens') = 0 then
    raise exception 'Adicione pelo menos um item';
  end if;
  if coalesce(payload->>'data_compra','') !~ '^\d{2}/\d{2}/\d{4}$' then raise exception 'Informe a data no formato DD/MM/AAAA'; end if;
  if note_id_input is null then
    insert into public.notes(customer_id,data_compra,descricao,observacoes,public_visible_value,validated_at,validated_by)
    values ((payload->>'customer_id')::bigint,payload->>'data_compra',coalesce(payload->>'descricao',''),
      coalesce(payload->>'observacoes',''),coalesce((payload->>'public_visible_value')::boolean,true),now(),
      (select name from public.profiles where id = auth.uid())) returning * into saved;
  else
    update public.notes set customer_id=(payload->>'customer_id')::bigint,data_compra=payload->>'data_compra',
      descricao=coalesce(payload->>'descricao',''),observacoes=coalesce(payload->>'observacoes',''),
      public_visible_value=coalesce((payload->>'public_visible_value')::boolean,true),updated_at=now()
    where id=note_id_input returning * into saved;
    if not found then raise exception 'Nota não encontrada'; end if;
    delete from public.note_items where note_id=note_id_input;
  end if;
  for item in select * from jsonb_array_elements(payload->'itens') loop
    insert into public.note_items(note_id,descricao,quantidade,valor_unitario)
    values(saved.id,trim(item->>'descricao'),(item->>'quantidade')::numeric,(item->>'valor_unitario')::numeric);
  end loop;
  update public.notes set valor_total=(select sum(valor_total) from public.note_items where note_id=saved.id)
  where id=saved.id returning * into saved;
  return jsonb_build_object('success',true,'id',saved.id,'public_id',saved.public_id,'numero_nota',saved.numero_nota,
    'message','Nota ' || saved.numero_nota || ' salva com sucesso.');
end;
$$;
revoke all on function public.save_note(jsonb,bigint) from public, anon;
grant execute on function public.save_note(jsonb,bigint) to authenticated;

-- Only the server may access legacy password hashes during the first login.
create table private.legacy_users (
  id bigint primary key, username text unique not null, email text unique not null,
  name text not null, role text not null, password_hash text,
  migrated_user_id uuid references auth.users(id), created_at timestamptz not null default now()
);
create index legacy_users_migrated_idx on private.legacy_users(migrated_user_id);
alter table private.legacy_users enable row level security;
grant all on private.legacy_users to service_role;
-- Called only by the Auth table trigger, never as a browser RPC.
create function private.create_profile() returns trigger language plpgsql security definer
set search_path = '' as $$
declare login_name text; legacy_id bigint;
begin
  login_name := lower(trim(new.raw_user_meta_data->>'username'));
  if login_name is null or login_name !~ '^[a-z0-9_.-]{3,60}$' then raise exception 'Nome de usuário inválido'; end if;
  legacy_id := (new.raw_app_meta_data->>'legacy_user_id')::bigint;
  if legacy_id is null and exists (select 1 from private.legacy_users where username=login_name or lower(email)=lower(new.email)) then
    raise exception 'Esta conta já existe. Use o login existente';
  end if;
  insert into public.profiles(id,username,email,name,role)
  values(new.id,login_name,lower(new.email),coalesce(nullif(trim(new.raw_user_meta_data->>'name'),''),login_name),'CLIENTE');
  if legacy_id is null then
    insert into public.customers(user_id,nome,email,cpf_cnpj,telefone,whatsapp)
    values(new.id,coalesce(nullif(trim(new.raw_user_meta_data->>'name'),''),login_name),lower(new.email),
      coalesce(new.raw_user_meta_data->>'cpf_cnpj',''),coalesce(new.raw_user_meta_data->>'telefone',''),coalesce(new.raw_user_meta_data->>'telefone',''));
  end if;
  return new;
end;
$$;
revoke all on function private.create_profile() from public, anon, authenticated;
create trigger fraga_auth_profile after insert on auth.users for each row execute function private.create_profile();
create function public.legacy_login_record(login text) returns jsonb
language sql security invoker set search_path = '' as $$
  select to_jsonb(u) from private.legacy_users u where username=lower(login) or lower(email)=lower(login) limit 1;
$$;
create function public.finish_legacy_login(legacy_id bigint, auth_id uuid) returns void
language plpgsql security invoker set search_path = '' as $$
declare old_user private.legacy_users;
begin
  select * into strict old_user from private.legacy_users where id=legacy_id for update;
  if old_user.migrated_user_id is not null and old_user.migrated_user_id <> auth_id then raise exception 'Conta já vinculada'; end if;
  insert into public.profiles(id,username,email,name,role)
    values(auth_id,old_user.username,old_user.email,old_user.name,old_user.role)
    on conflict(id) do update set role=excluded.role;
  update public.customers set user_id=auth_id where legacy_user_id=legacy_id;
  update private.legacy_users set migrated_user_id=auth_id,password_hash=null where id=legacy_id;
end;
$$;
revoke all on function public.legacy_login_record(text), public.finish_legacy_login(bigint,uuid) from public, anon, authenticated;
grant execute on function public.legacy_login_record(text), public.finish_legacy_login(bigint,uuid) to service_role;

-- Login throttling also covers the legacy password verification step.
create table private.login_attempts (key text primary key, attempts integer not null, started_at timestamptz not null);
alter table private.login_attempts enable row level security;
grant all on private.login_attempts to service_role;
create function public.allow_login(attempt_key text) returns boolean
language plpgsql security invoker set search_path = '' as $$
declare total integer;
begin
  insert into private.login_attempts as a(key,attempts,started_at) values(attempt_key,1,now())
  on conflict(key) do update set attempts=case when a.started_at < now()-interval '15 minutes' then 1 else a.attempts+1 end,
    started_at=case when a.started_at < now()-interval '15 minutes' then now() else a.started_at end
  returning attempts into total;
  return total <= 20;
end;
$$;
revoke all on function public.allow_login(text) from public, anon, authenticated;
grant execute on function public.allow_login(text) to service_role;

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values ('company-images','company-images',true,5242880,array['image/jpeg','image/png','image/webp'])
on conflict(id) do nothing;
create policy company_images_admin on storage.objects for all to authenticated
using (bucket_id='company-images' and (select private.is_admin()))
with check (bucket_id='company-images' and (select private.is_admin()));
